version: '3.9'

services:
  nginx:
    image: nginx
    container_name: nginx
    environment:
    ports:
     - "80:80"
     - "444:444"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
      TZ: Asia/Seoul
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    command: redis-server --port 6379
    hostname: redis_test
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./redis_data:/data
  app:
    build: .
    depends_on: 
      - postgres
      - redis
    expose:
      - "3000"
    # nginx프록시를 통과하기 때문에 더 이상 호스트 포트로 노출 시킬 필요 없음
    # ports:
    #   - '3000:3000'
    volumes:
      - '.:/src/app'
      - '/c/Users/BJS/Desktop/projects/js-s-nestjs/node_modules'
